[package]
name = "qgb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.3"
clap = { version = "4.3.11", features = ["derive"] }
sdl2 = "0.35.2"